### ISSUE TITLE
develop broken for ~99min: missed .await removal in #12073 caused clippy/compile failure

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota#12143]
## What happened

`develop` failed to compile (clippy) for ~99 minutes, from #12073's merge (2026-07-03 09:29 UTC) until #12071 incidentally fixed it (11:08 UTC). All 3 merges landing in between (#12127, #12055, #12057) inherited the same break and self-cancelled the rest of their CI pipeline (`clippy` job fails → `clippy-cancel` job cancels the run, so the top-level run shows as "cancelled" rather than "failed").

```
error[E0277]: `()` is not a future
   --> crates/iota-core/src/unit_tests/authority_tests.rs:7228:10
        .await;
         ^^^^^ `()` is not a future
error: could not compile `iota-core` (lib test) due to 1 previous error
```

Runs: [28651613139](https://github.com/iotaledger/iota/actions/runs/28651613139) (#12073), [28651962604](https://github.com/iotaledger/iota/actions/runs/28651962604) (#12127), [28652245213](https://github.com/iotaledger/iota/actions/runs/28652245213) (#12055), [28652278613](https://github.com/iotaledger/iota/actions/runs/28652278613) (#12057). Fixed by [efc8e49](https://github.com/iotaledger/iota/commit/efc8e49575112ad01a8d8a3b7973f86cc1c716a4) (#12071).

## Root cause

#12073 de-async'd `AuthorityState::insert_genesis_object(s)` and dropped `.await` at call sites, but PR's last CI run (2026-06-30) was 3 days stale relative to the commit that was actually merged (2026-07-03) — one `insert_genesis_objects(...).await` call site in `authority_tests.rs` wasn't covered by that stale CI run and slipped through. Not flaky/nondeterministic — a straight compile error, and not caused by concurrent-push cancellation (the `clippy` step itself failed before the cancel job ran).

## Suggested fix

Require PR branches to be up to date with `develop` (or re-run required checks on the latest commit) before merge is allowed, to prevent stale-CI merges like this.

No code changes needed now — already fixed on `develop`. Filing for tracking/visibility only.

**Comment by Thoralf-M** [comment]
> Require PR branches to be up to date with develop

Considering this for the future
